name: Runners Exercice

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]

    defaults:
      - run: 
        working_directory: node-app
    
    name: Node ${{ matrix.node }} sample

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache-dependency-path: node-app/package-lock.json

      - run: npm ci
      - run: npm test